//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoExchange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
                
        }

        public int TransactionID { get; set; }
        public Nullable<bool> Buy { get; set; }
        public string CurrencyFrom { get; set; }
        public Nullable<decimal> CurrencyFromAmount { get; set; }
        public string CurrencyTo { get; set; }
        public string CurrencyToAmount { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
